### ISSUE TITLE
HttpChannel calls unsupported close() on 400-600 HTTP codes

### ISSUE THREAD

**Issue by roded** [puniverse/comsat#49]
Hi,
Seems like HttpChannel is calling its close() on HTTP errors (400-600) and redirects.
This seems to make it impossible to return HTTP errors without an UnsupportedOperationException.
Or is there something I missed?

**Comment by circlespainter** [comment]
Can you try with `0.6.0-SNAPSHOT`?

**Comment by roded** [comment]
Same behaviour.
Should I submit a PR which removes the close() calls?

**Comment by circlespainter** [comment]
I see it's still present in `comsat-actors-servlet`, is that the backend you're using?

It should be been fixed already in the Sonatype-published `0.6.0-SNAPSHOT` artifacts for `comsat-actors-undertow` and `comsat-actors-netty` (which at present are from the `webperf` branch performance improvements).

Thanks for proposing a PR but I'd rather do it myself as I'd like to refactor few more things according to the latest performance work done in the Netty and Undertow backends.

Also, if you're not forced to use servlets I suggest you to consider the Netty or Undertow ones as they're faster (because they integrate the backend's native API directly).

**Comment by roded** [comment]
Yeah, I've been using comsat-actors-servlet.
I'll switch promptly.

Is there a release date for 0.6.0?

**Comment by circlespainter** [comment]
No but probably it won't be long.

**Comment by circlespainter** [comment]
A new `0.6.0-SNAPSHOT` should be available on Sonatype with a fix.

**Comment by circlespainter** [comment]
[0.6.0](https://github.com/puniverse/comsat/releases/tag/v0.6.0) released.
