### ISSUE TITLE
Hibernate-orm support

### ISSUE THREAD

**Issue by hsestupin** [puniverse/comsat#57]
Recently I've tried to use FiberDataSource from comsat-jdbc. But it can't be used along with hibernate. I've started to add instrumentation manually through **suspendables** file but it seems to be a lot of work. So are there any plans to support hibernate instrumentation by quasar team?

**Comment by pron** [comment]
Hi.
Even though Hibernate will work with Quasar in Java 9 (which would make all instrumentation completely transparent and not require any annotation of suspendable methods), we don't plan on supporting Hibernate beforehand or even officially afterwards. The reason is that Hibernate's design is pretty much antithetical to the lightweight threading concept, as it requires incredibly deep stacks.

For ORM solutions that work well with fibers (and are officially supported), take a look at [JDBI](http://jdbi.org/) and [jOOQ](http://www.jooq.org/). Unless you need to support legacy code, I think you'll find they work better than Hibernate, anyway.

**Comment by hsestupin** [comment]
Thanks! I'll give it a shot
